### PR TITLE
Add support for Python 3

### PR DESCRIPTION
**Pull request by Fawers**
Hi! Since this is such an interesting project, I decided to put in some lovely support for Python 3. Hope you don't mind it. :smile:

### CODE REVIEW

**Comment by erezsh** [comment]
Is this really the only change required for Python 3?  I assumed there would be a need to add & adjust some magic methods.

Anyway, I'm okay with this patch.

**Comment by erezsh** [comment]
Also, I don't mean to sound negative. Thank you for your contribution :)

**Comment by Fawers** [comment]
While I might have missed something in the magic methods, I don't see anything failing so far.

And thanks for the merge!

testing

**Comment by erezsh** [comment]
:+1:

**Pull request merged**
